version: '3'
services:
  para:
    image: lufia/para:latest
    restart: always
    environment:
      - PARA_APP_NAME=scoold
      - PARA_APP_SECRET_KEY=hogehoge
  parasetup:
    build: ./parasetup
    volumes:
      - ./volumes/para:/var/lib/para
    links:
      - para:para
    restart: on-failure
    environment:
      - ACCESS_KEY_PATH=/var/lib/para/access_key
      - SECRET_KEY_PATH=/var/lib/para/secret_key
  scoold:
    image: lufia/scoold:latest
    volumes:
      - ./volumes/para:/var/lib/para
    links:
      - para:para
    ports:
      - "8000:8000"
    restart: always
    environment:
      - SECRET_KEY_PATH=/var/lib/para/secret_key
      - ACCESS_KEY_PATH=/var/lib/para/access_key
      - PARA_APP_NAME=scoold
      - PARA_PORT=8000
      - PARA_ENV=production
      - PARA_HOST_URL=http://localhost:8000
      - PARA_ENDPOINT=http://para:8080
      - PARA_PASSWORD_AUTH_ENABLED=true
      - PARA_CODE_HIGHLIGHTING_ENABLED=true
      # - para_support_email=
      # - para_mail_host=smtp.gmail.com
      # - para_mail_port=587
      # - para_mail_username=
      # - para_mail_password=
      # - para_mail_tls=true
      # - para_mail_ssl=false
